services:

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /letsencrypt/live/apollo.com.ph:/etc/nginx/certs:ro
      - ./logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: /home/ubuntu/acs-zeep
      dockerfile: Dockerfile
    container_name: acs-fe
    ports:
      - "8080:80"  # Change port as necessary
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acs-be
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ./logs:/app/logs
    ports:
      - "7547:7547"
    networks:
      - app-network
    depends_on:
      - frontend
    command: ./mvnw spring-boot:run

networks:
  app-network:
    driver: bridge
